// Central export file for all icons used in the application
import { 
  IconChevronDown, 
  IconMail, 
  IconSearch, 
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconEye, 
  IconEyeOff,
  IconX,
  IconPlus,
  IconTrash,
  IconPencil,
  IconCheck,
  IconUserPlus,
  IconUsers,
  IconUserMinus,
  IconUserOff,
  IconUserCheck,
  IconUserExclamation,
  // New icons added for ProjectCardModel
  IconCalendar,
  IconUserCircle,
  IconClipboardList,
  IconFileText,
  IconBriefcase,
  IconCode,
  IconFileDescription
} from '@tabler/icons-react';

export {
  IconChevronDown,
  IconMail,
  IconSearch,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconEye, 
  IconEyeOff,
  IconX,
  IconPlus,
  IconTrash,
  IconPencil,
  IconCheck,
  IconUserPlus,
  IconUsers,
  IconUserMinus,
  IconUserOff,
  IconUserCheck,
  IconUserExclamation,
  // New icons added for ProjectCardModel
  IconCalendar,
  IconUserCircle,
  IconClipboardList,
  IconFileText,
  IconBriefcase,
  IconCode,
  IconFileDescription
};